const ActionsTypes = {
	//  LOGIN
	GET_CURRENT_USER: 'GET_CURRENT_USER',
	GET_LOGOUT: 'GET_LOGOUT',
	GET_LOGIN: 'GET_LOGIN',
	GET_LOGIN_SUCCESS: 'GET_LOGIN_SUCCESS',
	GET_LOGIN_FAILURE: 'GET_LOGIN_FAILURE',

	//  FORGOT PASSWORD
	POST_NEW_PASSWORD: 'POST_NEW_PASSWORD',
	POST_NEW_PASSWORD_SUCCESS: 'POST_NEW_PASSWORD_SUCCESS',
	POST_NEW_PASSWORD_FAILURE: 'POST_NEW_PASSWORD_FAILURE',

	RESET_STATUS: 'RESET_STATUS',

	// GLOBAL LOADING
	START_LOADING: 'START_LOADING',
	END_LOADING: 'END_LOADING',

	// TOAST
	HYDRATE_TOAST: 'HYDRATE_TOAST',
	CLOSE_TOAST: 'CLOSE_TOAST',
	OPEN_NEXT: 'OPEN_NEXT',

	// ERRORS
	CREATE_ERROR: 'CREATE_ERROR',
	CREATE_CRITICAL_ERROR: 'CREATE_CRITICAL_ERROR',
	CREATE_MAINTENANCE_MODE: 'CREATE_MAINTENANCE_MODE',

	// MODAL
	HYDRATE_MODAL: 'HYDRATE_MODAL',
	CLOSE_MODAL: 'CLOSE_MODAL',
	CLOSE_MODAL_REDIRECT: 'CLOSE_MODAL_REDIRECT',

	// MODAL TOOLTIP HELP
	OPEN_TOOLTIP_HELP: 'OPEN_TOOLTIP_HELP',
	CLOSE_TOOLTIP_HELP: 'CLOSE_TOOLTIP_HELP',

	// EXPORT DATAS
	POST_EXPORT_DATAS: 'POST_EXPORT_DATAS',
	POST_EXPORT_DATAS_SUCCESS: 'POST_EXPORT_DATAS_SUCCESS',
	POST_EXPORT_DATAS_FAILURE: 'POST_EXPORT_DATAS_FAILURE',

	// DATA FETCHER
	START_DATA_FETCHER: 'START_DATA_FETCHER',
	END_DATA_FETCHER: 'END_DATA_FETCHER',
}

export default ActionsTypes
