export enum userPrivileges {
	USERS_MANAGE_VIEW_MENU = 1,
	STOCK_MANAGE_TRACKING_GCA_VIEW_MENU = 11,
	INVENTORY_MANAGE_HISTORY_VIEW_MENU = 14,
	RETURN_TRACKING_VIEW_MENU = 4,
	POSE_TRACKING_VIEW_MENU = 8,
	USERS_MANAGE_ACTION_LIST = 3,
	INVENTORY_MANAGE_HISTORY_ACTION_LIST = 16,
}